image: smartbcity/gitlab-ci-jdk8:latest

stages:
  - build
  - verify
  - version
  - package
  - push

.version:
  stage: version
  image: smartbcity/gitlab-ci-semantic-versioning:latest
  script:
    - make -f /opt/io.smart-b/semantic-versioning/Makefile next_version >> version.build
  artifacts:
    paths:
      - version*

.package:
  stage: package
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make package -e VERSION=${VERSION_BUILD}

.push:
  stage: push
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make push -e VERSION=${VERSION_BUILD}

.push-latest:
  stage: push
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make push-latest -e VERSION=${VERSION_BUILD}

package-branch:
  extends: .package
  before_script:
    - echo branch > version.build
  only:
    refs:
      - branches
  artifacts:
    paths:
      - version*

push-branch:
  extends: .push
  only:
    refs:
      - branches
  when: manual

package-master:
  extends: .package
  before_script:
    - echo master > version.build
  only:
    refs:
      - master
  when: manual
  artifacts:
    paths:
      - version*

push-master:
  extends: .push
  only:
    refs:
      - master
  when: manual

version-tags:
  extends: .version
  only:
    - tags

package-tags:
  extends: .package
  only:
    - tags

push-tags:
  extends: .push
  only:
    - tags

push-latest-tags:
  extends: .push-latest
  only:
    - tags
