name: "Make Actions"
description: "Run lint, build, test, and package commands using make"
inputs:
  node-version:
    description: "Node version"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Node ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
        cache: "yarn"
    - name: Setup Yarn Cache
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: actions/cache@v4
      with:
        path: "**/dist"
        key: ${{ runner.os }}-dist-${{ hashFiles('**/yarn.lock') }}
