name: Dev

on:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - '*'

jobs:
  dev:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@a245ec857278ff19f131a9e724facc64ee25d7d0
    permissions:
      contents: read
      packages: write
    secrets:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_PKG_NPMJS_TOKEN: ${{ secrets.NPM_PKG_NPMJS_TOKEN}}
    with:
      with-publish-docker-registry-login: false
      with-stage-docker-registry-login: false
      with-promote-docker-registry-login: false
      on-tag: 'publish promote'

  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@a245ec857278ff19f131a9e724facc64ee25d7d0
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      make-file: 'Makefile_docs.mk'
      with-chromatic: true
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
