name: Dev

on: [push, workflow_dispatch]

jobs:
  dev:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@98fc8e4e9685554dc87e15fbcde14b77b4413deb
    permissions:
      contents: read
      packages: write
    secrets:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_PKG_NPMJS_TOKEN: ${{ secrets.NPM_PKG_NPMJS_TOKEN}}
    with:
      with-docker-registry-login: false

  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@98fc8e4e9685554dc87e15fbcde14b77b4413deb
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      storybook-dir: ''
      storybook-static-dir-separator: ''
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
