name: Docs Storybook

on: [push]
#on:
#  release:
#    types: [created]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn
      - name: Build StoryBook
        run: make build-storybook
      - uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static
  #      - uses: chromaui/action@v1
  #        with:
  #          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  #          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    #    permissions:
    #      pages: write
    #    environment:
    #      name: github-pages
    #      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build-storybook]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static

      #      - name: Setup Pages
      #        uses: actions/configure-pages@v4

      #      - name: Package and upload Pages artifact
      #        uses: actions/upload-pages-artifact@v3
      #        with:
      #          path: storybook-static

      #      - name: Deploy to GitHub Pages
      #        uses: actions/deploy-pages@v4

      - name: Print footer
        shell: bash
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Made by Komune" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "Update Me" >> $GITHUB_STEP_SUMMARY
