# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js Package

on: [push]
#on:
#  release:
#    types: [created]

jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    permissions:
  #      contents: read
  #      packages: write
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 18
  #          registry-url: https://npm.pkg.github.com
  #          scope: "@komune-io"
  #      - run: make package-libs
  #      - run: yarn workspaces run publish:gitlab
  #        env:
  #          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-packages:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set output
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      #      - uses: actions/cache@v2
      #        with:
      #          path: "**/node_modules"
      #          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v4
        with:
          path: "**/dist"
          key: ${{ runner.os }}-dist-${{ hashFiles('**/yarn.lock') }}

      - name: Build Libs
        run: make build-libs
