name: Libs Package

on: [push]
#on:
#  release:
#    types: [created]

jobs:
  package-libs:
    uses: komune-io/fixers-g2/.github/workflows/make-nodejs-workflow.yml@feat/libsCi
    permissions:
      contents: read
      packages: write
    with:
      make-file: "Makefile"

  package-storybook:
    uses: komune-io/fixers-g2/.github/workflows/make-nodejs-workflow.yml@feat/libsCi
    needs: [package-libs]
    permissions:
      contents: read
      packages: write
    with:
      make-file: "docs.mk"
      artifact-name: storybook-static
      artifact-path: ./storybook-static

  publish-chromatic:
    runs-on: ubuntu-latest
    name: Publish Chromatic
    needs: [package-storybook]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./storybook-static

      - name: Chromatic Footer
        shell: bash
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Made by Komune" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "Deploy to Chromatic  ${{ steps.chromatic.outputs.buildUrl }}" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "The Storybook preview URL  ${{ steps.chromatic.outputs.storybookUrl }}" >> $GITHUB_STEP_SUMMARY

  publish-github-page:
    runs-on: ubuntu-latest
    name: Publish Github Page
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [package-storybook]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Print footer
        shell: bash
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Made by Komune" >> $GITHUB_STEP_SUMMARY
          echo ""  >> $GITHUB_STEP_SUMMARY
          echo "Deploy to ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
