name: Reusable Dev Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: false
        type: "string"
        default: "21"
      make-file:
        description: "Node version"
        required: false
        type: "string"
        default: "Makefile"
      make-lint-task:
        description: "Make Command To Execute"
        required: false
        type: "string"
        default: "lint"
      make-build-task:
        description: "Make Command To Execute"
        required: false
        type: "string"
        default: "build"
      make-test-task:
        description: "Make Command To Execute"
        required: false
        type: "string"
        default: "test"
      make-package-task:
        description: "Make Command To Execute"
        required: false
        type: "string"
        default: "package"
      artifact-name:
        description: "Make Command To Execute"
        required: false
        type: "string"
      artifact-path:
        description: "Make Command To Execute"
        required: false
        type: "string"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
    steps:
      - name: Init NodeJs
        uses: komune-io/fixers-g2/.github/actions/nodejs@feat/libsCi
        with:
          node-version: ${{ inputs.node-version }}
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Make Commands and Upload Artifact
        uses: komune-io/fixers-g2/.github/actions/make-package@feat/libsCi
        with:
          make-file: ${{ inputs.make-file }}
          make-lint-task: ${{ inputs.make-lint-task }}
          make-build-task: ${{ inputs.make-build-task }}
          make-test-task: ${{ inputs.make-test-task }}
          make-package-task: ${{ inputs.make-package-task }}
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: ${{ inputs.artifact-path }}
